### ISSUE TITLE
Cell would show incorrect image once de-queued from reuse pool

### ISSUE THREAD

**Issue by borischou** [chiahsien/CHTCollectionViewWaterfallLayout#110]
I tried this framework in both my app and your sample, image would be rendered differently every time scrolling down or up.

Cats picture would show differently.

Is this designed or bug?

**Comment by yanamura3** [comment]
@borischou 

It seems demo code set cat image when initialize cell. So image will change every time scrolling down or up because cell is reused.

If you write your own code, you should set image when cellForItemAtIndexPath.
https://github.com/chiahsien/CHTCollectionViewWaterfallLayout/blob/develop/Demo/Demo/ViewController.m#L103-L109

**Comment by chiahsien** [comment]
I just fixed the demo codes, thanks!
