### ISSUE TITLE
Headers implementation?

### ISSUE THREAD

**Issue by lokeshu2opian** [chiahsien/CHTCollectionViewWaterfallLayout#6]
Is there a way using which I can implement Collection Headers in your control?

Thanks

**Comment by rene-dohan** [comment]
So this layout also don't support header and footer ? Because I see there headerheight but I am getting exception
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'no UICollectionViewLayoutAttributes instance for -layoutAttributesForSupplementaryElementOfKind: UICollectionElementKindSectionHeader at path <NSIndexPath: 0xc000000000000016> {length = 2, path = 0 - 0}'

**Comment by chiahsien** [comment]
@rene-dohan 

Have you tried this?

```objc
/// A supplementary view that identifies the header for a given section.
extern NSString *const CHTCollectionElementKindSectionHeader;
/// A supplementary view that identifies the footer for a given section.
extern NSString *const CHTCollectionElementKindSectionFooter;
```
